import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { SCHEDULE_BY_DOW, EN_COUNTERPART, enSlugFor, urlPathFor } from '../ukeplan.js';

/**
 * Ukeplanen skal finnes ett sted.
 *
 * FEILEN DENNE TESTEN FINNES FOR
 *
 * `generate-week.ts` og `assemble-week.ts` hadde hver sin kopi av planen, og
 * de var uenige om tre av seks dager. Innholdet ble laget og lastet opp under
 * ett navn, og lett etter under et annet. Manifestet meldte «no content
 * generated by GHA», som leses som «det var lite å ta av» og ikke som «vi
 * kastet det vi lagde».
 *
 * Målt 7. september 2026: `2026-09-09/teater` hadde 12 filer og
 * `2026-09-11/denne-helgen` hadde 14, mens begge dagene sto som hoppet over i
 * manifestet. Halvparten av ukens innhold forsvant, hver uke, uten at noe ble
 * rødt noe sted.
 *
 * DERFOR SJEKKER DEN TO TING. At planen er den forventede, og, viktigere, at
 * ingen av de to filene har laget seg en egen kopi igjen. Den første alene
 * ville ikke fanget feilen, siden begge kopiene var gyldige hver for seg.
 */

const SOCIAL = resolve(import.meta.dirname, '..');
const les = (f: string) => readFileSync(resolve(SOCIAL, f), 'utf8');

describe('ukeplanen har én fasit', () => {
	it('dekker mandag til lørdag, og ikke søndag', () => {
		expect([...SCHEDULE_BY_DOW.keys()].sort()).toEqual([1, 2, 3, 4, 5, 6]);
		expect(SCHEDULE_BY_DOW.has(7)).toBe(false);
	});

	it('har den avtalte samlingen på hver dag', () => {
		const faktisk = [...SCHEDULE_BY_DOW.entries()]
			.sort(([a], [b]) => a - b)
			.map(([dow, d]) => [dow, d.slug]);

		expect(faktisk).toEqual([
			[1, 'gratis'],
			[2, 'utstillinger'],
			[3, 'teater'],
			[4, 'denne-helgen'],
			// Fredag er konserter. IKKE denne-helgen, som ville gitt samme
			// samling to dager på rad, og IKKE uteliv, som ble prøvd først og
			// forkastet fordi nightlife hadde ett brukbart sted mot kravet om
			// fire. Endres dette, skal det være en beslutning målt på steder
			// med promo-samtykke, ikke en gjenganger fra en gammel kopi.
			[5, 'konserter'],
			[6, 'i-dag']
		]);
	});

	it('gir hver dag et ikke-tomt navn og en etikett', () => {
		for (const [dow, d] of SCHEDULE_BY_DOW) {
			expect(d.dayOfWeek, `dayOfWeek stemmer ikke for ${dow}`).toBe(dow);
			expect(d.dayName.no.length).toBeGreaterThan(0);
			expect(d.dayName.en.length).toBeGreaterThan(0);
			expect(d.label.length).toBeGreaterThan(0);
		}
	});

	it('bruker slugs som finnes som samlinger på gaari.no', () => {
		const collections = readFileSync(
			resolve(SOCIAL, '../../src/lib/collections.ts'),
			'utf8'
		);
		for (const d of SCHEDULE_BY_DOW.values()) {
			expect(collections, `${d.slug} finnes ikke i collections.ts`).toContain(
				`slug: '${d.slug}'`
			);
		}
		for (const en of Object.values(EN_COUNTERPART)) {
			expect(collections, `${en} finnes ikke i collections.ts`).toContain(`slug: '${en}'`);
		}
	});
});

describe('ingen egen kopi av planen', () => {
	// Dette er sperren. Uten den kan de to filene drive fra hverandre igjen,
	// og testen over ville fortsatt vært grønn.
	for (const fil of ['generate-week.ts', 'assemble-week.ts']) {
		it(`${fil} importerer planen i stedet for å definere den`, () => {
			const kode = les(fil);
			expect(kode, `${fil} mangler importen fra ukeplan`).toMatch(
				/from '\.\/ukeplan\.js'/
			);
			expect(kode, `${fil} definerer sin egen SCHEDULE_BY_DOW`).not.toMatch(
				/(const|let)\s+SCHEDULE_BY_DOW\s*=/
			);
			expect(kode, `${fil} definerer sin egen EN_COUNTERPART`).not.toMatch(
				/(const|let)\s+EN_COUNTERPART\s*=/
			);
		});
	}
});

describe('engelske ruter', () => {
	it('faller tilbake på den norske sluggen når ingen engelsk finnes', () => {
		expect(enSlugFor('teater')).toBe('teater');
		expect(urlPathFor('teater')).toBe('no/teater');
	});

	it('bruker den engelske ruta der den finnes', () => {
		expect(enSlugFor('denne-helgen')).toBe('this-weekend');
		expect(urlPathFor('denne-helgen')).toBe('en/this-weekend');
	});
});
