/**
 * Assemble a week manifest + per-day ZIPs from content already in Supabase
 * storage (generated by GHA daily jobs). No FFmpeg needed.
 *
 * Per day creates:
 *   - stories.zip  (story JPGs + handles.txt with IG handles + links)
 *   - carousel.zip (carousel JPGs + captions.txt with NO + EN captions)
 *   - reel MP4 linked directly from storage
 *
 * Usage:
 *   cd scripts && npx tsx social/assemble-week.ts --start=2026-04-06
 */
import 'dotenv/config';
import { createWriteStream, readFileSync, unlinkSync, mkdirSync, existsSync } from 'fs';
import { resolve } from 'path';
import archiver from 'archiver';
import { supabase } from '../lib/supabase.js';
import { getCollection } from '../../src/lib/collections.js';

const BUCKET = 'social-media';
const BASE_URL = `${process.env.PUBLIC_SUPABASE_URL}/storage/v1/object/public/social-media`;

const START_ARG = process.argv.find(a => a.startsWith('--start='))?.split('=')[1];
if (!START_ARG) {
	console.error('Usage: npx tsx social/assemble-week.ts --start=YYYY-MM-DD');
	process.exit(1);
}

interface DaySchedule {
	dayOfWeek: number;
	dayName: string;
	slug: string;
	label: string;
}

const SCHEDULE_BY_DOW = new Map<number, DaySchedule>([
	[1, { dayOfWeek: 1, dayName: 'Mandag', slug: 'gratis', label: 'Gratis denne uka' }],
	[2, { dayOfWeek: 2, dayName: 'Tirsdag', slug: 'teater', label: 'Teater denne uka' }],
	[3, { dayOfWeek: 3, dayName: 'Onsdag', slug: 'utstillinger', label: 'Utstillinger denne uka' }],
	[4, { dayOfWeek: 4, dayName: 'Torsdag', slug: 'denne-helgen', label: 'Helgens høydepunkter' }],
	[5, { dayOfWeek: 5, dayName: 'Fredag', slug: 'uteliv', label: 'Uteliv i helgen' }],
	[6, { dayOfWeek: 6, dayName: 'Lørdag', slug: 'i-dag', label: 'Lørdagens program' }]
]);

const EN_COUNTERPART: Record<string, string> = {
	'denne-helgen': 'this-weekend',
	'i-dag': 'today-in-bergen',
	'gratis': 'free-things-to-do-bergen'
};

function safeFilename(s: string): string {
	return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '')
		.replace(/[æø]/g, c => (c === 'æ' ? 'ae' : 'o'))
		.replace(/å/g, 'a').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function addDays(dateStr: string, days: number): string {
	const d = new Date(`${dateStr}T12:00:00`);
	d.setDate(d.getDate() + days);
	return d.toLocaleDateString('sv-SE', { timeZone: 'Europe/Oslo' });
}

function isoDayOfWeek(dateStr: string): number {
	const d = new Date(`${dateStr}T12:00:00+02:00`);
	const js = d.getDay();
	return js === 0 ? 7 : js;
}

function saturdayOfWeek(dateStr: string): string {
	const dow = isoDayOfWeek(dateStr);
	return addDays(dateStr, dow <= 6 ? 6 - dow : -1);
}

interface StoryEntry { url: string; venue: string; igHandle: string | null; title: string }

interface DayManifest {
	dayOfWeek: number;
	dayName: string;
	dateStr: string;
	slug: string;
	label: string;
	landingUrl: string;
	mp4Url: string | null;
	caption: string | null;
	storyCount: number;
	frameCount: number;
	durationSec: number;
	skipped: boolean;
	skipReason?: string;
	storiesZipUrl?: string;
	carouselZipUrl?: string;
	storyLink?: string;
	captionNo?: string;
	captionEn?: string;
}

async function listFiles(prefix: string): Promise<string[]> {
	const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;
	const url = process.env.PUBLIC_SUPABASE_URL!;
	const res = await fetch(`${url}/storage/v1/object/list/social-media`, {
		method: 'POST',
		headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' },
		body: JSON.stringify({ prefix, limit: 50 })
	});
	if (!res.ok) return [];
	const items = await res.json() as { name: string }[];
	return items.map(i => i.name);
}

async function fetchBuffer(url: string): Promise<Buffer | null> {
	try {
		const res = await fetch(url);
		if (!res.ok) return null;
		return Buffer.from(await res.arrayBuffer());
	} catch { return null; }
}

async function buildStoriesZip(
	d: DayManifest,
	files: string[],
	stories: StoryEntry[],
	startDate: string,
	tmpDir: string,
	sharp: typeof import('sharp').default
): Promise<string | null> {
	const storyFiles = files.filter(f => f.startsWith('story-') && f.endsWith('.png')).sort();
	if (storyFiles.length === 0) return null;

	const dayNameSafe = safeFilename(d.dayName);
	const slugSafe = safeFilename(d.slug);
	const zipPath = resolve(tmpDir, `${d.dateStr}-${slugSafe}-stories.zip`);
	const entries: { name: string; buffer: Buffer }[] = [];

	for (let i = 0; i < storyFiles.length; i++) {
		const buf = await fetchBuffer(`${BASE_URL}/${d.dateStr}/${d.slug}/${storyFiles[i]}`);
		if (buf) {
			const jpgBuf = await sharp(buf).jpeg({ quality: 88 }).toBuffer();
			const idx = String(i + 1).padStart(2, '0');
			entries.push({ name: `${dayNameSafe}-${slugSafe}-story-${idx}.jpg`, buffer: jpgBuf });
		}
	}

	if (entries.length === 0) return null;

	// handles.txt
	if (stories.length > 0) {
		const lines = [`Stories ${d.dayName} ${d.dateStr} — ${d.label}`, '', 'filnavn — venue — @-handle — link', ''];
		for (let i = 0; i < stories.length; i++) {
			const s = stories[i];
			const idx = String(i + 1).padStart(2, '0');
			const fname = `${dayNameSafe}-${slugSafe}-story-${idx}.jpg`;
			const venueSlug = safeFilename(s.venue) || `story-${idx}`;
			const link = `https://gaari.no/no/${d.slug}?utm_source=instagram&utm_medium=story&utm_campaign=${d.slug}&utm_content=${venueSlug}`;
			const handle = s.igHandle ? `@${s.igHandle}` : '(ingen IG)';
			lines.push(`${fname} — ${s.venue} — ${handle} — ${link}`);
		}
		entries.push({ name: 'handles.txt', buffer: Buffer.from(lines.join('\n'), 'utf-8') });
	}

	await archiveEntries(zipPath, entries);
	return await uploadZip(zipPath, `week/${startDate}/${d.dateStr}-${slugSafe}-stories.zip`);
}

async function buildCarouselZip(
	d: DayManifest,
	files: string[],
	startDate: string,
	tmpDir: string
): Promise<string | null> {
	const carouselFiles = files.filter(f => f.startsWith('carousel-') && f.endsWith('.jpg')).sort();
	if (carouselFiles.length === 0) return null;

	const slugSafe = safeFilename(d.slug);
	const zipPath = resolve(tmpDir, `${d.dateStr}-${slugSafe}-carousel.zip`);
	const entries: { name: string; buffer: Buffer }[] = [];

	for (const f of carouselFiles) {
		const buf = await fetchBuffer(`${BASE_URL}/${d.dateStr}/${d.slug}/${f}`);
		if (buf) entries.push({ name: f, buffer: buf });
	}

	if (entries.length === 0) return null;

	// captions.txt with NO + EN
	const collection = getCollection(d.slug);
	if (collection) {
		const noUrl = `https://gaari.no/no/${d.slug}?utm_source=facebook&utm_medium=group&utm_campaign=carousel`;
		const enSlug = EN_COUNTERPART[d.slug] || d.slug;
		const enPath = EN_COUNTERPART[d.slug] ? `en/${enSlug}` : `no/${d.slug}`;
		const enUrl = `https://gaari.no/${enPath}?utm_source=facebook&utm_medium=group&utm_campaign=carousel-en`;

		// Base caption from storage, swap URL for each language
		let baseCaption = d.caption || '';
		const noCaption = baseCaption
			? baseCaption.replace(/https:\/\/gaari\.no\/(?:no|en)\/[^\s?]+(\?[^\s]*)?/g, noUrl)
			: `Se alle: ${noUrl}`;
		const enCaption = baseCaption
			? baseCaption.replace(/https:\/\/gaari\.no\/(?:no|en)\/[^\s?]+(\?[^\s]*)?/g, enUrl)
			: `See all: ${enUrl}`;

		const lines = [
			`Captions for ${d.dayName} ${d.dateStr} — ${d.label}`,
			`${carouselFiles.length} slides`, '',
			'--- NORSK ---',
			noCaption, '',
			'--- ENGLISH ---',
			enCaption
		];
		entries.push({ name: 'captions.txt', buffer: Buffer.from(lines.join('\n'), 'utf-8') });

		// Store captions in manifest for copy buttons
		d.captionNo = noCaption;
		d.captionEn = enCaption;
	}

	await archiveEntries(zipPath, entries);
	return await uploadZip(zipPath, `week/${startDate}/${d.dateStr}-${slugSafe}-carousel.zip`);
}

async function archiveEntries(zipPath: string, entries: { name: string; buffer: Buffer }[]) {
	await new Promise<void>((ok, fail) => {
		const out = createWriteStream(zipPath);
		const ar = archiver('zip', { zlib: { level: 6 } });
		out.on('close', ok); out.on('error', fail); ar.on('error', fail);
		ar.pipe(out);
		for (const e of entries) ar.append(e.buffer, { name: e.name });
		ar.finalize();
	});
}

async function uploadZip(zipPath: string, storagePath: string): Promise<string | null> {
	const { error } = await supabase.storage.from(BUCKET).upload(
		storagePath, readFileSync(zipPath),
		{ contentType: 'application/zip', upsert: true }
	);
	try { unlinkSync(zipPath); } catch { /* */ }
	if (error) { console.warn(`  ZIP upload failed: ${error.message}`); return null; }
	const { data } = supabase.storage.from(BUCKET).getPublicUrl(storagePath);
	return data.publicUrl;
}

async function main() {
	const startDate = START_ARG!;
	const endSaturday = saturdayOfWeek(startDate);
	const tmpDir = resolve(import.meta.dirname, '.reels-tmp');
	if (!existsSync(tmpDir)) mkdirSync(tmpDir, { recursive: true });

	const dates: string[] = [];
	let cursor = startDate;
	while (cursor <= endSaturday) { dates.push(cursor); cursor = addDays(cursor, 1); }

	console.log(`Assembling week ${startDate} → ${endSaturday}\n`);

	const sharp = (await import('sharp')).default;
	const days: DayManifest[] = [];

	for (const dateStr of dates) {
		const dow = isoDayOfWeek(dateStr);
		const schedule = SCHEDULE_BY_DOW.get(dow);
		if (!schedule) continue;

		const prefix = `${dateStr}/${schedule.slug}/`;
		const files = await listFiles(prefix);

		if (files.length === 0) {
			console.log(`  ${dateStr} ${schedule.slug}: no content, skipping`);
			days.push({
				...schedule, dateStr,
				landingUrl: `https://gaari.no/r/${dateStr}/${schedule.slug}`,
				mp4Url: null, caption: null, storyCount: 0, frameCount: 0, durationSec: 0,
				skipped: true, skipReason: 'no content generated by GHA'
			});
			continue;
		}

		const storyFiles = files.filter(f => f.startsWith('story-') && f.endsWith('.png'));
		const carouselFiles = files.filter(f => f.startsWith('carousel-') && f.endsWith('.jpg'));
		const hasReel = files.includes('reel.mp4');

		let caption = '';
		try {
			const res = await fetch(`${BASE_URL}/${dateStr}/${schedule.slug}/caption.txt`);
			if (res.ok) caption = await res.text();
		} catch { /* */ }

		// Fetch stories manifest
		let stories: StoryEntry[] = [];
		if (files.includes('stories.json')) {
			try {
				const res = await fetch(`${BASE_URL}/${dateStr}/${schedule.slug}/stories.json`);
				if (res.ok) stories = await res.json();
			} catch { /* */ }
		}

		const noUrl = `https://gaari.no/no/${schedule.slug}`;
		const enSlug = EN_COUNTERPART[schedule.slug];
		const storyLink = enSlug ? noUrl : noUrl; // always NO link for stories

		const day: DayManifest = {
			...schedule, dateStr,
			landingUrl: `https://gaari.no/r/${dateStr}/${schedule.slug}`,
			mp4Url: hasReel ? `${BASE_URL}/${dateStr}/${schedule.slug}/reel.mp4` : null,
			caption,
			storyCount: storyFiles.length,
			frameCount: carouselFiles.length,
			durationSec: hasReel ? carouselFiles.length * 3 : 0,
			skipped: false,
			storyLink: noUrl
		};

		console.log(`  ${dateStr} ${schedule.slug}: ${carouselFiles.length} carousel, ${storyFiles.length} stories, reel=${hasReel}`);

		// Build stories ZIP
		const storiesZipUrl = await buildStoriesZip(day, files, stories, startDate, tmpDir, sharp);
		if (storiesZipUrl) {
			day.storiesZipUrl = storiesZipUrl;
			console.log(`    Stories ZIP: ok`);
		}

		// Build carousel ZIP (also sets captionNo/captionEn on day)
		const carouselZipUrl = await buildCarouselZip(day, files, startDate, tmpDir);
		if (carouselZipUrl) {
			day.carouselZipUrl = carouselZipUrl;
			console.log(`    Carousel ZIP: ok`);
		}

		days.push(day);
	}

	// Upload manifest
	const manifest = { startMonday: startDate, endSaturday, generatedAt: new Date().toISOString(), days };
	const { error } = await supabase.storage.from(BUCKET).upload(
		`week/${startDate}/manifest.json`,
		Buffer.from(JSON.stringify(manifest, null, 2), 'utf-8'),
		{ contentType: 'application/json; charset=utf-8', upsert: true }
	);
	if (error) { console.error(`Manifest upload failed: ${error.message}`); process.exit(1); }

	const successCount = days.filter(d => !d.skipped).length;
	console.log(`\nDone! ${successCount}/${days.length} days.`);
	console.log(`Page: https://gaari.no/r/week/${startDate}`);
}

main().catch(err => { console.error(err); process.exit(1); });
