/**
 * Assemble a week manifest + per-day ZIPs from content that already exists in
 * Supabase storage (generated by GHA daily jobs). Does NOT require FFmpeg.
 *
 * Each day gets its own ZIP containing: carousel JPGs, stories as JPGs,
 * reel MP4, caption.txt, and handles.txt with IG handles + UTM links.
 *
 * Usage:
 *   cd scripts && npx tsx social/assemble-week.ts --start=2026-04-06
 */
import 'dotenv/config';
import { createWriteStream, readFileSync, unlinkSync, mkdirSync, existsSync } from 'fs';
import { resolve } from 'path';
import archiver from 'archiver';
import { supabase } from '../lib/supabase.js';
import { getCollection } from '../../src/lib/collections.js';

const BUCKET = 'social-media';
const BASE_URL = `${process.env.PUBLIC_SUPABASE_URL}/storage/v1/object/public/social-media`;

const START_ARG = process.argv.find(a => a.startsWith('--start='))?.split('=')[1];
if (!START_ARG) {
	console.error('Usage: npx tsx social/assemble-week.ts --start=YYYY-MM-DD');
	process.exit(1);
}

interface DaySchedule {
	dayOfWeek: number;
	dayName: string;
	slug: string;
	label: string;
}

const SCHEDULE_BY_DOW = new Map<number, DaySchedule>([
	[1, { dayOfWeek: 1, dayName: 'Mandag', slug: 'gratis', label: 'Gratis denne uka' }],
	[2, { dayOfWeek: 2, dayName: 'Tirsdag', slug: 'teater', label: 'Teater denne uka' }],
	[3, { dayOfWeek: 3, dayName: 'Onsdag', slug: 'utstillinger', label: 'Utstillinger denne uka' }],
	[4, { dayOfWeek: 4, dayName: 'Torsdag', slug: 'denne-helgen', label: 'Helgens høydepunkter' }],
	[5, { dayOfWeek: 5, dayName: 'Fredag', slug: 'uteliv', label: 'Uteliv i helgen' }],
	[6, { dayOfWeek: 6, dayName: 'Lørdag', slug: 'i-dag', label: 'Lørdagens program' }]
]);

interface FbGroup { id: string; name: string; lang: 'no' | 'en'; allowSlugs?: string[] }

const FB_GROUPS: FbGroup[] = [
	{ id: 'hva-skjer-bergen', name: 'Hva skjer i Bergen', lang: 'no' },
	{ id: 'hva-skjer-bergen-i-dag', name: 'Hva skjer i bergen i dag', lang: 'no', allowSlugs: ['i-dag', 'today-in-bergen'] },
	{ id: 'det-skjer-bergen', name: 'Det Skjer i Bergen', lang: 'no' },
	{ id: 'bergen-expats', name: 'Bergen Expats', lang: 'en' }
];

const EN_COUNTERPART: Record<string, string> = {
	'denne-helgen': 'this-weekend',
	'i-dag': 'today-in-bergen',
	'gratis': 'free-things-to-do-bergen'
};

function safeFilename(s: string): string {
	return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '')
		.replace(/[æø]/g, c => (c === 'æ' ? 'ae' : 'o'))
		.replace(/å/g, 'a').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function addDays(dateStr: string, days: number): string {
	const d = new Date(`${dateStr}T12:00:00`);
	d.setDate(d.getDate() + days);
	return d.toLocaleDateString('sv-SE', { timeZone: 'Europe/Oslo' });
}

function isoDayOfWeek(dateStr: string): number {
	const d = new Date(`${dateStr}T12:00:00+02:00`);
	const js = d.getDay();
	return js === 0 ? 7 : js;
}

function saturdayOfWeek(dateStr: string): string {
	const dow = isoDayOfWeek(dateStr);
	return addDays(dateStr, dow <= 6 ? 6 - dow : -1);
}

interface StoryEntry { url: string; venue: string; igHandle: string | null; title: string }

interface DayManifest {
	dayOfWeek: number;
	dayName: string;
	dateStr: string;
	slug: string;
	label: string;
	landingUrl: string;
	mp4Url: string | null;
	caption: string | null;
	storyCount: number;
	frameCount: number;
	durationSec: number;
	skipped: boolean;
	skipReason?: string;
	dayZipUrl?: string;
}

async function listFiles(prefix: string): Promise<string[]> {
	const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;
	const url = process.env.PUBLIC_SUPABASE_URL!;
	const res = await fetch(`${url}/storage/v1/object/list/social-media`, {
		method: 'POST',
		headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' },
		body: JSON.stringify({ prefix, limit: 50 })
	});
	if (!res.ok) return [];
	const items = await res.json() as { name: string }[];
	return items.map(i => i.name);
}

async function fetchBuffer(url: string): Promise<Buffer | null> {
	try {
		const res = await fetch(url);
		if (!res.ok) return null;
		return Buffer.from(await res.arrayBuffer());
	} catch { return null; }
}

async function buildDayZip(
	d: DayManifest,
	files: string[],
	startDate: string,
	tmpDir: string,
	sharp: typeof import('sharp').default
): Promise<string | null> {
	const dayNameSafe = safeFilename(d.dayName);
	const slugSafe = safeFilename(d.slug);
	const zipName = `${d.dateStr}-${dayNameSafe}-${slugSafe}.zip`;
	const zipPath = resolve(tmpDir, zipName);

	const entries: { name: string; buffer: Buffer }[] = [];

	// Carousel JPGs
	const carouselFiles = files.filter(f => f.startsWith('carousel-') && f.endsWith('.jpg')).sort();
	for (const f of carouselFiles) {
		const buf = await fetchBuffer(`${BASE_URL}/${d.dateStr}/${d.slug}/${f}`);
		if (buf) entries.push({ name: `carousel/${f}`, buffer: buf });
	}

	// Stories → convert PNG to JPG
	const storyFiles = files.filter(f => f.startsWith('story-') && f.endsWith('.png')).sort();
	for (let i = 0; i < storyFiles.length; i++) {
		const buf = await fetchBuffer(`${BASE_URL}/${d.dateStr}/${d.slug}/${storyFiles[i]}`);
		if (buf) {
			const jpgBuf = await sharp(buf).jpeg({ quality: 88 }).toBuffer();
			const idx = String(i + 1).padStart(2, '0');
			entries.push({ name: `stories/${dayNameSafe}-${slugSafe}-story-${idx}.jpg`, buffer: jpgBuf });
		}
	}

	// Reel MP4
	if (files.includes('reel.mp4')) {
		const buf = await fetchBuffer(`${BASE_URL}/${d.dateStr}/${d.slug}/reel.mp4`);
		if (buf) entries.push({ name: `reel.mp4`, buffer: buf });
	}

	// Caption
	if (files.includes('caption.txt')) {
		const buf = await fetchBuffer(`${BASE_URL}/${d.dateStr}/${d.slug}/caption.txt`);
		if (buf) entries.push({ name: 'caption.txt', buffer: buf });
	}

	// Stories handles.txt
	let stories: StoryEntry[] = [];
	if (files.includes('stories.json')) {
		try {
			const res = await fetch(`${BASE_URL}/${d.dateStr}/${d.slug}/stories.json`);
			if (res.ok) stories = await res.json();
		} catch { /* */ }
	}

	if (Array.isArray(stories) && stories.length > 0) {
		const lines = [`Stories for ${d.dayName} ${d.dateStr} — ${d.label}`, '', 'filnavn — venue — @-handle — link', ''];
		for (let i = 0; i < stories.length; i++) {
			const s = stories[i];
			const idx = String(i + 1).padStart(2, '0');
			const fname = `${dayNameSafe}-${slugSafe}-story-${idx}.jpg`;
			const venueSlug = safeFilename(s.venue) || `story-${idx}`;
			const link = `https://gaari.no/no/${d.slug}?utm_source=instagram&utm_medium=story&utm_campaign=${d.slug}&utm_content=${venueSlug}`;
			const handle = s.igHandle ? `@${s.igHandle}` : '(ingen IG)';
			lines.push(`${fname} — ${s.venue} — ${handle} — ${link}`);
		}
		entries.push({ name: 'stories/handles.txt', buffer: Buffer.from(lines.join('\n'), 'utf-8') });
	}

	// FB group captions
	const collection = getCollection(d.slug);
	if (collection && carouselFiles.length > 0) {
		const captionLines: string[] = [
			`Carousels for ${d.dayName} ${d.dateStr} — ${d.label}`,
			`${carouselFiles.length} slides`, '',
			'En caption per FB-gruppe (ulik UTM-tag):', ''
		];
		for (const group of FB_GROUPS) {
			if (group.allowSlugs && !group.allowSlugs.includes(d.slug)) continue;
			let urlPath: string;
			if (group.lang === 'en') {
				const enSlug = EN_COUNTERPART[d.slug] || d.slug;
				urlPath = EN_COUNTERPART[d.slug] ? `en/${enSlug}` : `no/${d.slug}`;
			} else {
				urlPath = `no/${d.slug}`;
			}
			const url = `https://gaari.no/${urlPath}?utm_source=facebook&utm_medium=group&utm_campaign=${group.id}`;

			// Use existing caption.txt as base and swap the URL
			let baseCaption = d.caption || `Se alle: ${url}`;
			baseCaption = baseCaption.replace(/https:\/\/gaari\.no\/(?:no|en)\/[^\s?]+(\?[^\s]*)?/g, url);

			captionLines.push(`--- ${group.name} (${group.lang.toUpperCase()}) ---`);
			captionLines.push(baseCaption);
			captionLines.push('');
		}
		entries.push({ name: 'carousel/captions.txt', buffer: Buffer.from(captionLines.join('\n'), 'utf-8') });
	}

	if (entries.length === 0) return null;

	await new Promise<void>((ok, fail) => {
		const out = createWriteStream(zipPath);
		const ar = archiver('zip', { zlib: { level: 6 } });
		out.on('close', ok); out.on('error', fail); ar.on('error', fail);
		ar.pipe(out);
		for (const e of entries) ar.append(e.buffer, { name: e.name });
		ar.finalize();
	});

	const storagePath = `week/${startDate}/${d.dateStr}-${slugSafe}.zip`;
	const { error } = await supabase.storage.from(BUCKET).upload(
		storagePath, readFileSync(zipPath),
		{ contentType: 'application/zip', upsert: true }
	);
	try { unlinkSync(zipPath); } catch { /* */ }

	if (error) {
		console.warn(`  ZIP upload failed for ${d.dateStr}: ${error.message}`);
		return null;
	}

	const { data } = supabase.storage.from(BUCKET).getPublicUrl(storagePath);
	return data.publicUrl;
}

async function main() {
	const startDate = START_ARG!;
	const endSaturday = saturdayOfWeek(startDate);
	const tmpDir = resolve(import.meta.dirname, '.reels-tmp');
	if (!existsSync(tmpDir)) mkdirSync(tmpDir, { recursive: true });

	const dates: string[] = [];
	let cursor = startDate;
	while (cursor <= endSaturday) { dates.push(cursor); cursor = addDays(cursor, 1); }

	console.log(`Assembling week ${startDate} → ${endSaturday}\n`);

	const sharp = (await import('sharp')).default;
	const days: DayManifest[] = [];

	for (const dateStr of dates) {
		const dow = isoDayOfWeek(dateStr);
		const schedule = SCHEDULE_BY_DOW.get(dow);
		if (!schedule) continue;

		const prefix = `${dateStr}/${schedule.slug}/`;
		const files = await listFiles(prefix);

		if (files.length === 0) {
			console.log(`  ${dateStr} ${schedule.slug}: no content, skipping`);
			days.push({
				...schedule, dateStr,
				landingUrl: `https://gaari.no/r/${dateStr}/${schedule.slug}`,
				mp4Url: null, caption: null, storyCount: 0, frameCount: 0, durationSec: 0,
				skipped: true, skipReason: 'no content generated by GHA'
			});
			continue;
		}

		const storyFiles = files.filter(f => f.startsWith('story-') && f.endsWith('.png'));
		const carouselFiles = files.filter(f => f.startsWith('carousel-') && f.endsWith('.jpg'));
		const hasReel = files.includes('reel.mp4');

		let caption = '';
		try {
			const res = await fetch(`${BASE_URL}/${dateStr}/${schedule.slug}/caption.txt`);
			if (res.ok) caption = await res.text();
		} catch { /* */ }

		const day: DayManifest = {
			...schedule, dateStr,
			landingUrl: `https://gaari.no/r/${dateStr}/${schedule.slug}`,
			mp4Url: hasReel ? `${BASE_URL}/${dateStr}/${schedule.slug}/reel.mp4` : null,
			caption,
			storyCount: storyFiles.length,
			frameCount: carouselFiles.length,
			durationSec: hasReel ? carouselFiles.length * 3 : 0,
			skipped: false
		};

		console.log(`  ${dateStr} ${schedule.slug}: ${carouselFiles.length} carousel, ${storyFiles.length} stories, reel=${hasReel}`);

		// Build per-day ZIP
		const zipUrl = await buildDayZip(day, files, startDate, tmpDir, sharp);
		if (zipUrl) {
			day.dayZipUrl = zipUrl;
			console.log(`    ZIP: ${zipUrl}`);
		}

		days.push(day);
	}

	// Upload manifest
	const manifest = {
		startMonday: startDate,
		endSaturday,
		generatedAt: new Date().toISOString(),
		days
	};

	const { error } = await supabase.storage.from(BUCKET).upload(
		`week/${startDate}/manifest.json`,
		Buffer.from(JSON.stringify(manifest, null, 2), 'utf-8'),
		{ contentType: 'application/json; charset=utf-8', upsert: true }
	);
	if (error) { console.error(`Manifest upload failed: ${error.message}`); process.exit(1); }

	const successCount = days.filter(d => !d.skipped).length;
	console.log(`\nDone! ${successCount}/${days.length} days.`);
	console.log(`Page: https://gaari.no/r/week/${startDate}`);
}

main().catch(err => { console.error(err); process.exit(1); });
