/**
 * Ukeplanen for sosiale medier. ÉN fasit.
 *
 * HVORFOR DENNE FILA FINNES
 *
 * Planen lå tidligere i to eksemplarer, ett i `generate-week.ts` og ett i
 * `assemble-week.ts`. De hadde drevet fra hverandre uten at noe ble rødt:
 *
 *   dag        generate lagde     assemble lette etter
 *   tirsdag    utstillinger       teater
 *   onsdag     teater             utstillinger
 *   fredag     denne-helgen       uteliv
 *
 * Følgen var at innholdet ble laget, lastet opp til lageret, og deretter lett
 * etter under et annet navn. Manifestet skrev «no content generated by GHA»,
 * som var feil: innholdet var generert, det lå bare et annet sted. Kontrollert
 * 7. september 2026, da `2026-09-09/teater` hadde 12 filer og
 * `2026-09-11/denne-helgen` hadde 14, mens begge dagene sto som hoppet over.
 *
 * Halvparten av ukens innhold ble kastet på gulvet hver uke, og den eneste
 * meldingen om det så ut som en normal beskjed om at det var lite å ta av.
 *
 * REGELEN: legger du til en dag eller bytter en samling, skjer det HER.
 * `ukeplan.test.ts` feiler hvis noen legger inn en egen kopi igjen.
 */

export interface DaySchedule {
	/** ISO: 1 = mandag, 6 = lørdag. Søndag har ingen post. */
	dayOfWeek: number;
	dayName: { no: string; en: string };
	/** Samlingens slug på gaari.no. Også mappenavnet i lageret. */
	slug: string;
	label: string;
}

/**
 * Fredag er `konserter`.
 *
 * TO VALG, DET FØRSTE VAR FEIL. `generate-week.ts` lagde helgeinnhold både
 * torsdag og fredag, altså samme samling to dager på rad. Fredag ble derfor
 * satt til `uteliv` 7. september 2026, på grunnlag av at nightlife hadde 11
 * arrangementer med bilde de neste 14 dagene.
 *
 * Det tallet var målt med feil instrument. Kravet i `MIN_EVENTS_FOR_POST` er
 * fire ulike STEDER, ikke fire arrangementer, og SoMe-innhold hentes bare fra
 * kilder med skriftlig ja til promotering, ikke bare til visning. Målt med
 * begge betingelsene inne hadde nightlife **ett** brukbart sted. `uteliv`
 * kunne aldri ha produsert en post.
 *
 * `konserter` har 7 steder og virker i dag. Skulle nightlife vokse seg stort
 * nok senere, er uteliv fortsatt et godt fredagstema, men det skal måles på
 * steder med promo-samtykke før noen bytter tilbake.
 */
/**
 * ETIKETTENE LOVER IKKE ET TIDSVINDU SAMLINGEN IKKE HAR.
 *
 * Fram til 8. september 2026 het mandag «Gratis denne uka» og fredag
 * «Konserter i helgen». Ingen av de to samlingene er avgrenset slik.
 * `gratis` er definert som de neste to ukene, og captionen 7. september
 * listet arrangementer 14. og 18. september under «denne uka».
 * Fredagsposten lovet «i helgen» og listet 14., 17. og 21. september.
 *
 * Det ble vurdert aa stramme UTVALGET til etikettens vindu i stedet. Maalt
 * 8. september ville det tatt fredag fra sju til tre steder, altsaa under
 * kravet paa fire, og dagen ville falt bort helt. Etiketten var det som var
 * galt, ikke utvalget.
 *
 * `denne-helgen` (torsdag) og `i-dag` (loerdag) BEHOLDER sine tidsetiketter.
 * De to samlingene er ekte datoavgrenset, og maalingen bekreftet det: 16 av
 * 16 steder innenfor helgen, og 12 av 13 samme dag.
 *
 * Regelen: en etikett med tidsord krever at samlingen faktisk filtrerer paa
 * den tiden. Ellers skal tidsordet ut.
 */
export const SCHEDULE_BY_DOW = new Map<number, DaySchedule>([
	[1, { dayOfWeek: 1, dayName: { no: 'Mandag', en: 'Monday' }, slug: 'gratis', label: 'Gratis i Bergen' }],
	[2, { dayOfWeek: 2, dayName: { no: 'Tirsdag', en: 'Tuesday' }, slug: 'utstillinger', label: 'Utstillinger i Bergen' }],
	[3, { dayOfWeek: 3, dayName: { no: 'Onsdag', en: 'Wednesday' }, slug: 'teater', label: 'Teater i Bergen' }],
	[4, { dayOfWeek: 4, dayName: { no: 'Torsdag', en: 'Thursday' }, slug: 'denne-helgen', label: 'Helgens høydepunkter' }],
	[5, { dayOfWeek: 5, dayName: { no: 'Fredag', en: 'Friday' }, slug: 'konserter', label: 'Konserter i Bergen' }],
	[6, { dayOfWeek: 6, dayName: { no: 'Lørdag', en: 'Saturday' }, slug: 'i-dag', label: 'Lørdagens program' }]
]);

/**
 * Norsk samlings-slug til den engelske ruta, der en finnes.
 *
 * Lå også i to eksemplarer, med samme innhold. Samme risiko.
 *
 * teater, utstillinger, uteliv og mat-og-drikke har ingen engelsk rute, og
 * faller tilbake på /no/-adressen.
 */
export const EN_COUNTERPART: Record<string, string> = {
	'denne-helgen': 'this-weekend',
	'i-dag': 'today-in-bergen',
	'gratis': 'free-things-to-do-bergen'
};

/** Engelsk slug for en norsk samling, eller den norske hvis ingen finnes. */
export function enSlugFor(slug: string): string {
	return EN_COUNTERPART[slug] ?? slug;
}

/** Ruta på gaari.no: engelsk der den finnes, ellers den norske. */
export function urlPathFor(slug: string): string {
	return EN_COUNTERPART[slug] ? `en/${EN_COUNTERPART[slug]}` : `no/${slug}`;
}

/**
 * Samlinger som FAKTISK filtrerer paa dato.
 *
 * Bare disse kan ha et tidsord i etiketten. `ukeplan.test.ts` haandhever det.
 * Alle andre samlinger spenner over flere uker, og et tidsord i etiketten
 * ville lovet leseren noe innholdet ikke holder.
 */
export const DATOAVGRENSEDE_SAMLINGER = new Set<string>([
	'denne-helgen',
	'this-weekend',
	'i-dag',
	'today-in-bergen',
	'i-kveld'
]);

/**
 * Tidsord som gjoer en etikett til et loefte om naar noe skjer.
 *
 * «Helgens hoeydepunkter» og «Loerdagens program» er greie, fordi samlingene
 * deres er datoavgrenset. «Gratis denne uka» var det ikke.
 */
const TIDSORD = /\b(i dag|i kveld|denne uk[ae]n?|i helgen|helgens|l\u00f8rdagens|s\u00f8ndagens|i morgen)\b/i;

/** Lover etiketten et tidsvindu samlingen ikke har? */
export function loverFeilTidsvindu(slug: string, label: string): boolean {
	return TIDSORD.test(label) && !DATOAVGRENSEDE_SAMLINGER.has(slug);
}
