/**
 * Ukeplanen for sosiale medier. ÉN fasit.
 *
 * HVORFOR DENNE FILA FINNES
 *
 * Planen lå tidligere i to eksemplarer, ett i `generate-week.ts` og ett i
 * `assemble-week.ts`. De hadde drevet fra hverandre uten at noe ble rødt:
 *
 *   dag        generate lagde     assemble lette etter
 *   tirsdag    utstillinger       teater
 *   onsdag     teater             utstillinger
 *   fredag     denne-helgen       uteliv
 *
 * Følgen var at innholdet ble laget, lastet opp til lageret, og deretter lett
 * etter under et annet navn. Manifestet skrev «no content generated by GHA»,
 * som var feil: innholdet var generert, det lå bare et annet sted. Kontrollert
 * 7. september 2026, da `2026-09-09/teater` hadde 12 filer og
 * `2026-09-11/denne-helgen` hadde 14, mens begge dagene sto som hoppet over.
 *
 * Halvparten av ukens innhold ble kastet på gulvet hver uke, og den eneste
 * meldingen om det så ut som en normal beskjed om at det var lite å ta av.
 *
 * REGELEN: legger du til en dag eller bytter en samling, skjer det HER.
 * `ukeplan.test.ts` feiler hvis noen legger inn en egen kopi igjen.
 */

export interface DaySchedule {
	/** ISO: 1 = mandag, 6 = lørdag. Søndag har ingen post. */
	dayOfWeek: number;
	dayName: { no: string; en: string };
	/** Samlingens slug på gaari.no. Også mappenavnet i lageret. */
	slug: string;
	label: string;
}

/**
 * Fredag er `konserter`.
 *
 * TO VALG, DET FØRSTE VAR FEIL. `generate-week.ts` lagde helgeinnhold både
 * torsdag og fredag, altså samme samling to dager på rad. Fredag ble derfor
 * satt til `uteliv` 7. september 2026, på grunnlag av at nightlife hadde 11
 * arrangementer med bilde de neste 14 dagene.
 *
 * Det tallet var målt med feil instrument. Kravet i `MIN_EVENTS_FOR_POST` er
 * fire ulike STEDER, ikke fire arrangementer, og SoMe-innhold hentes bare fra
 * kilder med skriftlig ja til promotering, ikke bare til visning. Målt med
 * begge betingelsene inne hadde nightlife **ett** brukbart sted. `uteliv`
 * kunne aldri ha produsert en post.
 *
 * `konserter` har 7 steder og virker i dag. Skulle nightlife vokse seg stort
 * nok senere, er uteliv fortsatt et godt fredagstema, men det skal måles på
 * steder med promo-samtykke før noen bytter tilbake.
 */
export const SCHEDULE_BY_DOW = new Map<number, DaySchedule>([
	[1, { dayOfWeek: 1, dayName: { no: 'Mandag', en: 'Monday' }, slug: 'gratis', label: 'Gratis denne uka' }],
	[2, { dayOfWeek: 2, dayName: { no: 'Tirsdag', en: 'Tuesday' }, slug: 'utstillinger', label: 'Utstillinger denne uka' }],
	[3, { dayOfWeek: 3, dayName: { no: 'Onsdag', en: 'Wednesday' }, slug: 'teater', label: 'Teater denne uka' }],
	[4, { dayOfWeek: 4, dayName: { no: 'Torsdag', en: 'Thursday' }, slug: 'denne-helgen', label: 'Helgens høydepunkter' }],
	[5, { dayOfWeek: 5, dayName: { no: 'Fredag', en: 'Friday' }, slug: 'konserter', label: 'Konserter i helgen' }],
	[6, { dayOfWeek: 6, dayName: { no: 'Lørdag', en: 'Saturday' }, slug: 'i-dag', label: 'Lørdagens program' }]
]);

/**
 * Norsk samlings-slug til den engelske ruta, der en finnes.
 *
 * Lå også i to eksemplarer, med samme innhold. Samme risiko.
 *
 * teater, utstillinger, uteliv og mat-og-drikke har ingen engelsk rute, og
 * faller tilbake på /no/-adressen.
 */
export const EN_COUNTERPART: Record<string, string> = {
	'denne-helgen': 'this-weekend',
	'i-dag': 'today-in-bergen',
	'gratis': 'free-things-to-do-bergen'
};

/** Engelsk slug for en norsk samling, eller den norske hvis ingen finnes. */
export function enSlugFor(slug: string): string {
	return EN_COUNTERPART[slug] ?? slug;
}

/** Ruta på gaari.no: engelsk der den finnes, ellers den norske. */
export function urlPathFor(slug: string): string {
	return EN_COUNTERPART[slug] ? `en/${EN_COUNTERPART[slug]}` : `no/${slug}`;
}
